// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BugStore.Infra.CompiledModels
{
    public partial class AppContextDbModel
    {
        private AppContextDbModel()
            : base(skipDetectChanges: false, modelId: new Guid("5d50dab2-9eb4-4cce-8f09-008dbd3f7876"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var customer = CustomerEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderLine = OrderLineEntityType.Create(this);
            var product = ProductEntityType.Create(this);

            OrderEntityType.CreateForeignKey1(order, customer);
            OrderLineEntityType.CreateForeignKey1(orderLine, order);
            OrderLineEntityType.CreateForeignKey2(orderLine, product);

            CustomerEntityType.CreateAnnotations(customer);
            OrderEntityType.CreateAnnotations(order);
            OrderLineEntityType.CreateAnnotations(orderLine);
            ProductEntityType.CreateAnnotations(product);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
