// <auto-generated />
using BugStore.Infra.CompiledModels;
using BugStore.Infra.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppContextDb), typeof(AppContextDbModel))]
